spring:
  datasource:
    url: "jdbc:h2:mem:hobby;MODE=MYSQL"
    password:
    username: admin
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 50
      connection-timeout: 50000
      connection-init-sql: SELECT 1
      validation-timeout: 20000
      minimum-idle: 25
      idle-timeout: 600000
      max-lifetime: 1800000
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        type: trace
server:
  tomcat:
    threads:
      max: 32
      min-spare: 16
      max-connections: 8192
      accept-count: 30
      connection-timeout: 20000
  port: 8080
