spring:
  datasource:
    url: 'jdbc:mysql://${DB_HOST}:3306/intorest?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8'
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: update
cloud:
  storage:
    gcs:
      bucket-name: ${STORAGE_BUCKET}

logging:
  level:
    org: info

server:
  port: 80